In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\sarathbabumallam\anaconda3\lib\site-packages (1.0.1)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\sarathbabumallam\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\sarathbabumallam\anaconda3\lib\site-packages (from pandas) (1.18.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\sarathbabumallam\anaconda3\lib\site-packages (from pandas) (2019.3)
Requirement already satisfied: six>=1.5 in c:\users\sarathbabumallam\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas) (1.14.0)

In [2]:
import pandas as pd

pd

In [5]:
sampleData = {
    'Sachin' : [100,105,50,20,95],
    'Sourav' : [183,101,19, 48,7]
}

scores = pd.DataFrame(sampleData)
scores

   Sachin  Sourav
0     100     183
1     105     101
2      50      19
3      20      48
4      95       7

In [6]:
data = {
    'orange' : [3,2,0,1],
    'apples' : [0,3,7,2]
    
}

#fruits = pd.DataFrame(data,index=['one','two','three','four'])
fruits = pd.DataFrame(data)

In [13]:
fruits.loc[0:,'apples']

0    0
1    3
2    7
3    2
Name: apples, dtype: int64

In [14]:
fruits.iloc[0:,]

   orange  apples
0       3       0
1       2       3
2       0       7
3       1       2

#

In [15]:
fruits.iloc[0:,0]

0    3
1    2
2    0
3    1
Name: orange, dtype: int64

In [16]:
fruits = pd.DataFrame(data,index=['one','two','three','four'])

In [28]:
fruits.iloc[2:,1]

three    7
four     2
Name: apples, dtype: int64

In [27]:
fruits.loc['three':,'orange']

three    0
four     1
Name: orange, dtype: int64

In [29]:
fruits

       orange  apples
one         3       0
two         2       3
three       0       7
four        1       2

In [31]:
fruits['orange']['two']

2

In [32]:
fruits.iloc[2]

orange    0
apples    7
Name: three, dtype: int64

In [34]:
import os

In [35]:
os.listdir()

['.DS_Store',
 '.ipynb_checkpoints',
 'database.db',
 'Exercise_pandas.ipynb',
 'IMDB-Movie-Data.csv',
 'new_purchases.csv',
 'new_purchases.json',
 'pandas practice.ipynb',
 'Pandas_basics.ipynb',
 'purchases.csv',
 'purchases.json',
 'Sample.csv',
 'Sample.xlsx']

In [36]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.

In [37]:
ls

 Volume in drive C is Windows
 Volume Serial Number is D63E-6211

 Directory of C:\Users\SarathBabuMallam\Desktop\Data science\Python\Inceptz-Batch13-Analytics_and_Python-master\Inceptz-Batch13-Analytics_and_Python-master\05 - Day 5 - Pandas with Exercises

17-04-2020  12:54    <DIR>          .
17-04-2020  12:54    <DIR>          ..
13-04-2020  14:29             6,148 .DS_Store
17-04-2020  11:52    <DIR>          .ipynb_checkpoints
13-04-2020  14:29            12,288 database.db
13-04-2020  14:29            14,360 Exercise_pandas.ipynb
13-04-2020  14:29           309,767 IMDB-Movie-Data.csv
13-04-2020  14:29                60 new_purchases.csv
13-04-2020  14:29               102 new_purchases.json
17-04-2020  12:54            10,542 pandas practice.ipynb
17-04-2020  12:46         1,096,340 Pandas_basics.ipynb
13-04-2020  14:29                60 purchases.csv
13-04-2020  14:29               102 purchases.json
13-04-2020  14:29                55 Sample.csv
13-04-2020  14:29             5,434 Sample.xlsx
              12 File(s)      1,455,258 bytes
               3 Dir(s)  328,315,432,960 bytes free

# Methods of reading Data into pandas dataframe!

In [40]:
#importing CSV files
df = pd.read_csv('us-500.csv')
df

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
0,James,Butt,"Benton, John B Jr",6649 N Blue Gum St,New Orleans,Orleans,LA,70116,504-621-8927,504-845-1427,jbutt@gmail.com,http://www.bentonjohnbjr.com
1,Josephine,Darakjy,"Chanay, Jeffrey A Esq",4 B Blue Ridge Blvd,Brighton,Livingston,MI,48116,810-292-9388,810-374-9840,josephine_darakjy@darakjy.org,http://www.chanayjeffreyaesq.com
2,Art,Venere,"Chemel, James L Cpa",8 W Cerritos Ave #54,Bridgeport,Gloucester,NJ,8014,856-636-8749,856-264-4130,art@venere.org,http://www.chemeljameslcpa.com
3,Lenna,Paprocki,Feltz Printing Service,639 Main St,Anchorage,Anchorage,AK,99501,907-385-4412,907-921-2010,lpaprocki@hotmail.com,http://www.feltzprintingservice.com
4,Donette,Foller,Printing Dimensions,34 Center St,Hamilton,Butler,OH,45011,513-570-1893,513-549-4561,donette.foller@cox.net,http://www.printingdimensions.com
...,...,...,...,...,...,...,...,...,...,...,...,...
495,Brittni,Gillaspie,Inner Label,67 Rv Cent,Boise,Ada,ID,83709,208-709-1235,208-206-9848,bgillaspie@gillaspie.com,http://www.innerlabel.com
496,Raylene,Kampa,Hermar Inc,2 Sw Nyberg Rd,Elkhart,Elkhart,IN,46514,574-499-1454,574-330-1884,rkampa@kampa.org,http://www.hermarinc.com
497,Flo,Bookamer,Simonton Howe & Schneider Pc,89992 E 15th St,Alliance,Box Butte,NE,69301,308-726-2182,308-250-6987,flo.bookamer@cox.net,http://www.simontonhoweschneiderpc.com
498,Jani,Biddy,Warehouse Office & Paper Prod,61556 W 20th Ave,Seattle,King,WA,98104,206-711-6498,206-395-6284,jbiddy@yahoo.com,http://www.warehouseofficepaperprod.com
499,Chauncey,Motley,Affiliated With Travelodge,63 E Aurora Dr,Orlando,Orange,FL,32804,407-413-4842,407-557-8857,chauncey_motley@aol.com,http://www.affiliatedwithtravelodge.com

In [41]:
df.loc[0]

first_name                             James
last_name                               Butt
company_name               Benton, John B Jr
address                   6649 N Blue Gum St
city                             New Orleans
county                               Orleans
state                                     LA
zip                                    70116
phone1                          504-621-8927
phone2                          504-845-1427
email                        jbutt@gmail.com
web             http://www.bentonjohnbjr.com
Name: 0, dtype: object

In [42]:
df.loc[0][0]

'James'

In [43]:
df.loc[0:,'zip']

0      70116
1      48116
2       8014
3      99501
4      45011
       ...
495    83709
496    46514
497    69301
498    98104
499    32804
Name: zip, Length: 500, dtype: int64

In [47]:
df.iloc[499:,2]

499    Affiliated With Travelodge
Name: company_name, dtype: object

In [51]:
rf = pd.read_csv('https://raw.githubusercontent.com/codeforamerica/ohana-api/master/data/sample-csv/addresses.csv')
rf

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,7,7,500 Arbor Road,NaN,Menlo Park,CA,94025,US
7,8,8,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
8,9,9,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
9,10,10,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
10,11,11,2140 Euclid Avenue.,NaN,Redwood City,CA,94061,US
11,12,12,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
12,13,13,399 Marine Parkway.,NaN,Redwood City,CA,94065,US
13,14,14,660 Veterans Blvd.,NaN,Redwood City,CA,94063,US
14,15,15,1500 Valencia Street,NaN,San Francisco,CA,94110,US
15,16,16,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [56]:
df = pd.read_json("purchases.json")
df

        apples  oranges
June         3        0
Robert       2        3
Lily         0        7
David        1        2

In [57]:
df.loc['June']

apples     3
oranges    0
Name: June, dtype: int64

In [58]:
df.loc['June']['apples']

3

In [59]:
df.iloc[2:,]

       apples  oranges
Lily        0        7
David       1        2

In [60]:
df.iloc[2:,1]

Lily     7
David    2
Name: oranges, dtype: int64

# How to open a database file

In [61]:
!pip install pysqlite3

Collecting pysqlite3
  Downloading pysqlite3-0.4.2.tar.gz (40 kB)
Building wheels for collected packages: pysqlite3
  Building wheel for pysqlite3 (setup.py): started
  Building wheel for pysqlite3 (setup.py): finished with status 'done'
  Running setup.py clean for pysqlite3
Failed to build pysqlite3
Installing collected packages: pysqlite3
    Running setup.py install for pysqlite3: started
    Running setup.py install for pysqlite3: finished with status 'done'
Successfully installed pysqlite3

  WARNING: Legacy build of wheel for 'pysqlite3' created no files.
  Command arguments: 'C:\Users\SarathBabuMallam\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\SARATH~1\\AppData\\Local\\Temp\\pip-install-e_n8ag1x\\pysqlite3\\setup.py'"'"'; __file__='"'"'C:\\Users\\SARATH~1\\AppData\\Local\\Temp\\pip-install-e_n8ag1x\\pysqlite3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\SARATH~1\AppData\Local\Temp\pip-wheel-bjzgc27o'
  Command output: [use --verbose to show]

In [62]:
import sqlite3 as sql

con = sql.connect('database.db')

In [75]:
df = pd.read_sql_query('SELECT * FROM purchases where apples >0',con)
df

    index  apples  oranges
0    June       3        0
1  Robert       2        3
2   David       1        2

In [76]:
df.size

9

In [77]:
len(df)

3

In [79]:
df = df.set_index('index')
df

        apples  oranges
index
June         3        0
Robert       2        3
David        1        2

In [80]:
df.size

6

# Writing it back into different formats

In [81]:
df.to_excel('sampleexcel.xlsx',index=False)

In [82]:
df.to_csv('sample,csv',sep=':')

# Important operations in a dataframe

In [147]:
movies_df = pd.read_csv("IMDB-Movie-Data.csv",index_col="Title")

In [84]:
movies_df

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [85]:
movies_df.shape

(1000, 11)

In [86]:
movies_df.head()

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [87]:
movies_df.head(10)

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
The Great Wall,6,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
La La Land,7,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
Mindhorn,8,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
The Lost City of Z,9,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
Passengers,10,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0

In [88]:
movies_df.tail()

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [89]:
movies_df.tail(10)

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Underworld: Rise of the Lycans,991,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.80,44.0
Taare Zameen Par,992,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0
Take Me Home Tonight,993,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,NaN
Resident Evil: Afterlife,994,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
Project X,995,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [90]:
movies_df.loc[movies_df['Rank']==991]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Underworld: Rise of the Lycans,991,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.8,44.0

In [93]:
movies_df.loc[(movies_df['Rank']==991)]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Underworld: Rise of the Lycans,991,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.8,44.0

In [94]:
movies_df.columns

Index(['Rank', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

AttributeError: 'DataFrame' object has no attribute 'rows'

In [96]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, Guardians of the Galaxy to Nine Lives
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Genre               1000 non-null   object
 2   Description         1000 non-null   object
 3   Director            1000 non-null   object
 4   Actors              1000 non-null   object
 5   Year                1000 non-null   int64
 6   Runtime (Minutes)   1000 non-null   int64
 7   Rating              1000 non-null   float64
 8   Votes               1000 non-null   int64
 9   Revenue (Millions)  872 non-null    float64
 10  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(4)
memory usage: 133.8+ KB

In [100]:
type(movies_df)

pandas.core.frame.DataFrame

In [101]:
movies_df.shape

(1000, 11)

# Duplicates

In [135]:
duplicates_df = movies_df.append(movies_df)

In [136]:
duplicates_df.shape

(2000, 11)

In [125]:
duplicates_df.loc[duplicates_df['Rank']==991]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Underworld: Rise of the Lycans,991,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.8,44.0
Underworld: Rise of the Lycans,991,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.8,44.0

In [126]:
duplicates_df = duplicates_df.drop_duplicates(inplace = False)
#not working

In [138]:
duplicates_df.shape

(2000, 11)

In [129]:
duplicates_df = duplicates_df.drop_duplicates(inplace = True)

In [137]:
duplicates_df.shape

(2000, 11)

In [139]:
duplicates_df = duplicates_df.drop_duplicates()

In [140]:
duplicates_df.shape

(1000, 11)

In [141]:
duplicates_df

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [148]:
movies_copy_df = movies_df

movies_copy_df['Rank']
movies_df['Rank']

Title
Guardians of the Galaxy       1
Prometheus                    2
Split                         3
Sing                          4
Suicide Squad                 5
                           ...
Secret in Their Eyes        996
Hostel: Part II             997
Step Up 2: The Streets      998
Search Party                999
Nine Lives                 1000
Name: Rank, Length: 1000, dtype: int64

In [149]:
movies_copy_df['Rank'] = range(1000,2000,1)

In [150]:
movies_df['Rank']

Title
Guardians of the Galaxy    1000
Prometheus                 1001
Split                      1002
Sing                       1003
Suicide Squad              1004
                           ...
Secret in Their Eyes       1995
Hostel: Part II            1996
Step Up 2: The Streets     1997
Search Party               1998
Nine Lives                 1999
Name: Rank, Length: 1000, dtype: int32

In [151]:
duplicate_df_rank = movies_df.append(movies_copy_df)

In [152]:
duplicate_df_rank['Rank']

Title
Guardians of the Galaxy    1000
Prometheus                 1001
Split                      1002
Sing                       1003
Suicide Squad              1004
                           ...
Secret in Their Eyes       1995
Hostel: Part II            1996
Step Up 2: The Streets     1997
Search Party               1998
Nine Lives                 1999
Name: Rank, Length: 2000, dtype: int32

In [154]:
duplicates_df

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [168]:
duplicate_df_rank.drop_duplicates(subset=['Rank','Year'],inplace = False)

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1000,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,1001,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,1002,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,1003,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,1004,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,1995,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,1996,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,1997,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,1998,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1999,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [169]:
duplicate_df_rank.shape
#not working

(1000, 11)

In [170]:
duplicate_df.drop_duplicates(inplace=True,keep=)
#not working

SyntaxError: invalid syntax (<ipython-input-170-5fac4161de81>, line 1)

In [161]:
movies_df.columns

Index(['Rank', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [162]:
movies_df.rename(columns= {
    "Description":"Desc",
    "Revenue (Millions)" : "Revenue",
    "Runtime (Minutes)":"Runtime"
},inplace = True)

In [163]:
movies_df.columns

Index(['Rank', 'Genre', 'Desc', 'Director', 'Actors', 'Year', 'Runtime',
       'Rating', 'Votes', 'Revenue', 'Metascore'],
      dtype='object')

In [171]:
movies_df

,Rank,Genre,Desc,Director,Actors,Year,Runtime,Rating,Votes,Revenue,Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1000,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,1001,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,1002,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,1003,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,1004,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,1995,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,1996,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,1997,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,1998,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1999,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [172]:
movies_df.columns

Index(['Rank', 'Genre', 'Desc', 'Director', 'Actors', 'Year', 'Runtime',
       'Rating', 'Votes', 'Revenue', 'Metascore'],
      dtype='object')

In [173]:
movies_df.values

array([[1000, 'Action,Adventure,Sci-Fi',
        'A group of intergalactic criminals are forced to work together to stop a fanatical warrior from taking control of the universe.',
        ..., 757074, 333.13, 76.0],
       [1001, 'Adventure,Mystery,Sci-Fi',
        'Following clues to the origin of mankind, a team finds a structure on a distant moon, but they soon realize they are not alone.',
        ..., 485820, 126.46, 65.0],
       [1002, 'Horror,Thriller',
        'Three girls are kidnapped by a man with a diagnosed 23 distinct personalities. They must try to escape before the apparent emergence of a frightful new 24th.',
        ..., 157606, 138.12, 62.0],
       ...,
       [1997, 'Drama,Music,Romance',
        'Romantic sparks occur between two dance students from different backgrounds at the Maryland School of the Arts.',
        ..., 70699, 58.01, 50.0],
       [1998, 'Adventure,Comedy',
        'A pair of friends embark on a mission to reunite their pal with the woman he was going to marry.',
        ..., 4881, nan, 22.0],
       [1999, 'Comedy,Family,Fantasy',
        "A stuffy businessman finds himself trapped inside the body of his family's cat.",
        ..., 12435, 19.64, 11.0]], dtype=object)

In [176]:
col_low = []
for col in movies_df:
    col = col.lower()
    col_low.append(col)
col_low

['rank',
 'genre',
 'desc',
 'director',
 'actors',
 'year',
 'runtime',
 'rating',
 'votes',
 'revenue',
 'metascore']

In [177]:
for i in movies_df:
    print(i)

Rank
Genre
Desc
Director
Actors
Year
Runtime
Rating
Votes
Revenue
Metascore

In [179]:
for i in movies_df.values:
    print(i)

[1000 'Action,Adventure,Sci-Fi'
 'A group of intergalactic criminals are forced to work together to stop a fanatical warrior from taking control of the universe.'
 'James Gunn' 'Chris Pratt, Vin Diesel, Bradley Cooper, Zoe Saldana' 2014
 121 8.1 757074 333.13 76.0]
[1001 'Adventure,Mystery,Sci-Fi'
 'Following clues to the origin of mankind, a team finds a structure on a distant moon, but they soon realize they are not alone.'
 'Ridley Scott'
 'Noomi Rapace, Logan Marshall-Green, Michael Fassbender, Charlize Theron'
 2012 124 7.0 485820 126.46 65.0]
[1002 'Horror,Thriller'
 'Three girls are kidnapped by a man with a diagnosed 23 distinct personalities. They must try to escape before the apparent emergence of a frightful new 24th.'
 'M. Night Shyamalan'
 'James McAvoy, Anya Taylor-Joy, Haley Lu Richardson, Jessica Sula' 2016
 117 7.3 157606 138.12 62.0]
[1003 'Animation,Comedy,Family'
 "In a city of humanoid animals, a hustling theater impresario's attempt to save his theater with a singing competition becomes grander than he anticipates even as its finalists' find that their lives will never be the same."
 'Christophe Lourdelet'
 'Matthew McConaughey,Reese Witherspoon, Seth MacFarlane, Scarlett Johansson'
 2016 108 7.2 60545 270.32 59.0]
[1004 'Action,Adventure,Fantasy'
 'A secret government agency recruits some of the most dangerous incarcerated super-villains to form a defensive task force. Their first mission: save the world from the apocalypse.'
 'David Ayer' 'Will Smith, Jared Leto, Margot Robbie, Viola Davis' 2016
 123 6.2 393727 325.02 40.0]
[1005 'Action,Adventure,Fantasy'
 'European mercenaries searching for black powder become embroiled in the defense of the Great Wall of China against a horde of monstrous creatures.'
 'Yimou Zhang' 'Matt Damon, Tian Jing, Willem Dafoe, Andy Lau' 2016 103
 6.1 56036 45.13 42.0]
[1006 'Comedy,Drama,Music'
 'A jazz pianist falls for an aspiring actress in Los Angeles.'
 'Damien Chazelle'
 'Ryan Gosling, Emma Stone, Rosemarie DeWitt, J.K. Simmons' 2016 128 8.3
 258682 151.06 93.0]
[1007 'Comedy'
 'A has-been actor best known for playing the title character in the 1980s detective series "Mindhorn" must work with the police when a serial killer says that he will only speak with Detective Mindhorn, whom he believes to be a real person.'
 'Sean Foley'
 'Essie Davis, Andrea Riseborough, Julian Barratt,Kenneth Branagh' 2016 89
 6.4 2490 nan 71.0]
[1008 'Action,Adventure,Biography'
 'A true-life drama, centering on British explorer Col. Percival Fawcett, who disappeared while searching for a mysterious city in the Amazon in the 1920s.'
 'James Gray'
 'Charlie Hunnam, Robert Pattinson, Sienna Miller, Tom Holland' 2016 141
 7.1 7188 8.01 78.0]
[1009 'Adventure,Drama,Romance'
 'A spacecraft traveling to a distant colony planet and transporting thousands of people has a malfunction in its sleep chambers. As a result, two passengers are awakened 90 years early.'
 'Morten Tyldum'
 'Jennifer Lawrence, Chris Pratt, Michael Sheen,Laurence Fishburne' 2016
 116 7.0 192177 100.01 41.0]
[1010 'Adventure,Family,Fantasy'
 "The adventures of writer Newt Scamander in New York's secret community of witches and wizards seventy years before Harry Potter reads his book in school."
 'David Yates'
 'Eddie Redmayne, Katherine Waterston, Alison Sudol,Dan Fogler' 2016 133
 7.5 232072 234.02 66.0]
[1011 'Biography,Drama,History'
 'The story of a team of female African-American mathematicians who served a vital role in NASA during the early years of the U.S. space program.'
 'Theodore Melfi'
 'Taraji P. Henson, Octavia Spencer, Janelle Monáe,Kevin Costner' 2016 127
 7.8 93103 169.27 74.0]
[1012 'Action,Adventure,Sci-Fi'
 'The Rebel Alliance makes a risky move to steal the plans for the Death Star, setting up the epic saga to follow.'
 'Gareth Edwards' 'Felicity Jones, Diego Luna, Alan Tudyk, Donnie Yen'
 2016 133 7.9 323118 532.17 65.0]
[1013 'Animation,Adventure,Comedy'
 "In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches an impetuous Chieftain's daughter's island, she answers the Ocean's call to seek out the Demigod to set things right."
 'Ron Clements'
 "Auli'i Cravalho, Dwayne Johnson, Rachel House, Temuera Morrison" 2016
 107 7.7 118151 248.75 81.0]
[1014 'Action,Comedy,Drama'
 'Gloria is an out-of-work party girl forced to leave her life in New York City, and move back home. When reports surface that a giant creature is destroying Seoul, she gradually comes to the realization that she is somehow connected to this phenomenon.'
 'Nacho Vigalondo'
 'Anne Hathaway, Jason Sudeikis, Austin Stowell,Tim Blake Nelson' 2016 109
 6.4 8612 2.87 70.0]
[1015 'Animation,Adventure,Comedy'
 'The quiet life of a terrier named Max is upended when his owner takes in Duke, a stray whom Max instantly dislikes.'
 'Chris Renaud' 'Louis C.K., Eric Stonestreet, Kevin Hart, Lake Bell' 2016
 87 6.6 120259 368.31 61.0]
[1016 'Biography,Drama,History'
 'WWII American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people, and becomes the first man in American history to receive the Medal of Honor without firing a shot.'
 'Mel Gibson'
 'Andrew Garfield, Sam Worthington, Luke Bracey,Teresa Palmer' 2016 139
 8.2 211760 67.12 71.0]
[1017 'Action,Thriller'
 "The CIA's most dangerous former operative is drawn out of hiding to uncover more explosive truths about his past."
 'Paul Greengrass'
 'Matt Damon, Tommy Lee Jones, Alicia Vikander,Vincent Cassel' 2016 123
 6.7 150823 162.16 58.0]
[1018 'Biography,Drama'
 'A five-year-old Indian boy gets lost on the streets of Calcutta, thousands of kilometers from home. He survives many challenges before being adopted by a couple in Australia. 25 years later, he sets out to find his lost family.'
 'Garth Davis' 'Dev Patel, Nicole Kidman, Rooney Mara, Sunny Pawar' 2016
 118 8.1 102061 51.69 69.0]
[1019 'Drama,Mystery,Sci-Fi'
 'When twelve mysterious spacecraft appear around the world, linguistics professor Louise Banks is tasked with interpreting the language of the apparent alien visitors.'
 'Denis Villeneuve'
 'Amy Adams, Jeremy Renner, Forest Whitaker,Michael Stuhlbarg' 2016 116
 8.0 340798 100.5 81.0]
[1020 'Adventure,Drama,Thriller'
 'Kenny Wells, a prospector desperate for a lucky break, teams up with a similarly eager geologist and sets off on a journey to find gold in the uncharted jungle of Indonesia.'
 'Stephen Gaghan'
 'Matthew McConaughey, Edgar Ramírez, Bryce Dallas Howard, Corey Stoll'
 2016 120 6.7 19053 7.22 49.0]
[1021 'Drama'
 "A depressed uncle is asked to take care of his teenage nephew after the boy's father dies."
 'Kenneth Lonergan'
 'Casey Affleck, Michelle Williams, Kyle Chandler,Lucas Hedges' 2016 137
 7.9 134213 47.7 96.0]
[1022 'Crime,Drama,Horror'
 "A cold-blooded predatory couple while cruising the streets in search of their next victim, will stumble upon a 17-year-old high school girl, who will be sedated, abducted and chained in the strangers' guest room."
 'Ben Young' 'Emma Booth, Ashleigh Cummings, Stephen Curry,Susie Porter'
 2016 108 6.7 1115 nan 72.0]
[1023 'Animation,Adventure,Comedy'
 'After the Bergens invade Troll Village, Poppy, the happiest Troll ever born, and the curmudgeonly Branch set off on a journey to rescue her friends.'
 'Walt Dohrn'
 'Anna Kendrick, Justin Timberlake,Zooey Deschanel, Christopher Mintz-Plasse'
 2016 92 6.5 38552 153.69 56.0]
[1024 'Action,Adventure,Sci-Fi'
 "Two decades after the first Independence Day invasion, Earth is faced with a new extra-Solar threat. But will mankind's new space defenses be enough?"
 'Roland Emmerich'
 'Liam Hemsworth, Jeff Goldblum, Bill Pullman,Maika Monroe' 2016 120 5.3
 127553 103.14 32.0]
[1025 'Comedy'
 'Fiona visits Paris for the first time to assist her myopic Aunt Martha. Catastrophes ensue, mainly involving Dom, a homeless man who has yet to have an emotion or thought he was afraid of expressing.'
 'Dominique Abel'
 'Fiona Gordon, Dominique Abel,Emmanuelle Riva, Pierre Richard' 2016 83
 6.8 222 nan nan]
[1026 'Action,Adventure,Drama'
 'In ancient India, an adventurous and daring man becomes involved in a decades old feud between two warring people.'
 'S.S. Rajamouli'
 'Prabhas, Rana Daggubati, Anushka Shetty,Tamannaah Bhatia' 2015 159 8.3
 76193 6.5 nan]
[1027 'Horror,Thriller'
 'A young woman must save herself and her friends from an ancient evil that stalks its victims through the real-life phenomenon of sleep paralysis.'
 'Phillip Guzman'
 'Jocelin Donahue, Jesse Bradford, Jesse Borrego,Lori Petty' 2016 99 4.7
 523 0.01 nan]
[1028 'Comedy'
 'When three overworked and under-appreciated moms are pushed beyond their limits, they ditch their conventional responsibilities for a jolt of long overdue freedom, fun, and comedic self-indulgence.'
 'Jon Lucas' 'Mila Kunis, Kathryn Hahn, Kristen Bell,Christina Applegate'
 2016 100 6.2 66540 113.08 60.0]
[1029 'Action,Adventure,Drama'
 'When Callum Lynch explores the memories of his ancestor Aguilar and gains the skills of a Master Assassin, he discovers he is a descendant of the secret Assassins society.'
 'Justin Kurzel'
 'Michael Fassbender, Marion Cotillard, Jeremy Irons,Brendan Gleeson' 2016
 115 5.9 112813 54.65 36.0]
[1030 'Comedy'
 "A holiday gathering threatens to go off the rails when Ned Fleming realizes that his daughter's Silicon Valley millionaire boyfriend is about to pop the question."
 'John Hamburg'
 'Zoey Deutch, James Franco, Tangie Ambrose,Cedric the Entertainer' 2016
 111 6.3 48123 60.31 39.0]
[1031 'Drama,Thriller'
 "A wealthy art gallery owner is haunted by her ex-husband's novel, a violent thriller she interprets as a symbolic revenge tale."
 'Tom Ford'
 'Amy Adams, Jake Gyllenhaal, Michael Shannon, Aaron Taylor-Johnson' 2016
 116 7.5 126030 10.64 67.0]
[1032 'Action,Adventure,Sci-Fi'
 "After the re-emergence of the world's first mutant, world-destroyer Apocalypse, the X-Men must unite to defeat his extinction level plan."
 'Bryan Singer'
 'James McAvoy, Michael Fassbender, Jennifer Lawrence, Nicholas Hoult'
 2016 144 7.1 275510 155.33 52.0]
[1033 'Action,Adventure,Comedy'
 'A fast-talking mercenary with a morbid sense of humor is subjected to a rogue experiment that leaves him with accelerated healing powers and a quest for revenge.'
 'Tim Miller' 'Ryan Reynolds, Morena Baccarin, T.J. Miller, Ed Skrein'
 2016 108 8.0 627797 363.02 65.0]
[1034 'Action,Horror,Sci-Fi'
 'Alice returns to where the nightmare began: The Hive in Raccoon City, where the Umbrella Corporation is gathering its forces for a final strike against the only remaining survivors of the apocalypse.'
 'Paul W.S. Anderson'
 'Milla Jovovich, Iain Glen, Ali Larter, Shawn Roberts' 2016 107 5.6 46165
 26.84 49.0]
[1035 'Action,Adventure,Sci-Fi'
 "Political interference in the Avengers' activities causes a rift between former allies Captain America and Iron Man."
 'Anthony Russo'
 'Chris Evans, Robert Downey Jr.,Scarlett Johansson, Sebastian Stan' 2016
 147 7.9 411656 408.08 75.0]
[1036 'Adventure,Drama,Sci-Fi'
 "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival."
 'Christopher Nolan'
 'Matthew McConaughey, Anne Hathaway, Jessica Chastain, Mackenzie Foy'
 2014 169 8.6 1047747 187.99 74.0]
[1037 'Action,Adventure,Fantasy'
 'While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.'
 'Scott Derrickson'
 'Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams, Benedict Wong'
 2016 115 7.6 293732 232.6 72.0]
[1038 'Action,Adventure,Western'
 'Seven gunmen in the old west gradually come together to help a poor village against savage thieves.'
 'Antoine Fuqua'
 "Denzel Washington, Chris Pratt, Ethan Hawke,Vincent D'Onofrio" 2016 132
 6.9 122853 93.38 54.0]
[1039 'Comedy,Drama'
 "Alienated, hopeful-filmmaker Pat Johnson's epic story growing up in rural Illinois, falling in love, and becoming the first fan of the movie that changed everything."
 'Patrick Read Johnson'
 'John Francis Daley, Austin Pendleton, Colleen Camp, Neil Flynn' 2007 113
 7.1 241 nan nan]
[1040 'Animation,Adventure,Comedy'
 'A sausage strives to discover the truth about his existence.'
 'Greg Tiernan' 'Seth Rogen, Kristen Wiig, Jonah Hill, Alistair Abell'
 2016 89 6.3 120690 97.66 66.0]
[1041 'Drama'
 'A chronicle of the childhood, adolescence and burgeoning adulthood of a young, African-American, gay man growing up in a rough neighborhood of Miami.'
 'Barry Jenkins'
 'Mahershala Ali, Shariff Earp, Duan Sanderson, Alex R. Hibbert' 2016 111
 7.5 135095 27.85 99.0]
[1042 'Horror'
 'A group of friends are going on a camping trip to celebrate graduating college. But once they enter the woods, the proverbial shit starts to hit the fan.'
 'Shawn Burkett'
 'Brittany Blanton, Ayse Howard, Roman Jossart,Nadia White' 2016 73 2.7
 496 nan nan]
[1043 'Biography,Drama,History'
 "The story of Ray Kroc, a salesman who turned two brothers' innovative fast food eatery, McDonald's, into one of the biggest restaurant businesses in the world with a combination of ambition, persistence, and ruthlessness."
 'John Lee Hancock'
 'Michael Keaton, Nick Offerman, John Carroll Lynch, Linda Cardellini'
 2016 115 7.2 37033 12.79 66.0]
[1044 'Drama'
 "A young street artist in East Los Angeles is caught between his father's obsession with lowrider car culture, his ex-felon brother and his need for self-expression."
 'Ricardo de Montreuil'
 'Gabriel Chavarria, Demián Bichir, Theo Rossi,Tony Revolori' 2016 99 6.3
 279 4.21 57.0]
[1045 'Action,Adventure,Fantasy'
 'Jack Sparrow and Barbossa embark on a quest to find the elusive fountain of youth, only to discover that Blackbeard and his daughter are after it too.'
 'Rob Marshall' 'Johnny Depp, Penélope Cruz, Ian McShane, Geoffrey Rush'
 2011 136 6.7 395025 241.06 45.0]
[1046 'Drama,Thriller'
 'In the high-stakes world of political power-brokers, Elizabeth Sloane is the most sought after and formidable lobbyist in D.C. But when taking on the most powerful opponent of her career, she finds winning may come at too high a price.'
 'John Madden'
 'Jessica Chastain, Mark Strong, Gugu Mbatha-Raw,Michael Stuhlbarg' 2016
 132 7.3 17818 3.44 64.0]
[1047 'Adventure,Drama,Fantasy'
 'A young girl finds herself in a reform school after therapy since she was blamed for the death of a young boy. At the school she finds herself drawn to a fellow student, unaware that he is an angel, and has loved her for thousands of years.'
 'Scott Hicks'
 'Hermione Corfield, Addison Timlin, Joely Richardson,Jeremy Irvine' 2016
 91 5.6 5103 nan nan]
[1048 'Action,Adventure,Sci-Fi'
 'The USS Enterprise crew explores the furthest reaches of uncharted space, where they encounter a new ruthless enemy who puts them and everything the Federation stands for to the test.'
 'Justin Lin' 'Chris Pine, Zachary Quinto, Karl Urban, Zoe Saldana' 2016
 122 7.1 164567 158.8 68.0]
[1049 'Drama'
 'A director (Charlize Theron) of an international aid agency in Africa meets a relief aid doctor (Javier Bardem) amidst a political/social revolution, and together face tough choices ... See full summary »'
 'Sean Penn'
 'Charlize Theron, Javier Bardem, Adèle Exarchopoulos,Jared Harris' 2016
 130 3.7 987 nan 16.0]
[1050 'Action,Adventure,Fantasy'
 'Three decades after the defeat of the Galactic Empire, a new threat arises. The First Order attempts to rule the galaxy and only a ragtag group of heroes can stop them, along with the help of the Resistance.'
 'J.J. Abrams' 'Daisy Ridley, John Boyega, Oscar Isaac, Domhnall Gleeson'
 2015 136 8.1 661608 936.63 81.0]
[1051 'Action,Adventure,Fantasy'
 'Vampire death dealer, Selene (Kate Beckinsale) fights to end the eternal war between the Lycan clan and the Vampire faction that betrayed her.'
 'Anna Foerster'
 'Kate Beckinsale, Theo James, Tobias Menzies, Lara Pulver' 2016 91 5.8
 41362 30.35 23.0]
[1052 'Comedy,Drama'
 "Three generations come together in the week leading up to Mother's Day."
 'Garry Marshall'
 'Jennifer Aniston, Kate Hudson, Julia Roberts, Jason Sudeikis' 2016 118
 5.6 20221 32.46 18.0]
[1053 'Action,Crime,Thriller'
 'An ex-hitman comes out of retirement to track down the gangsters that took everything from him.'
 'Chad Stahelski'
 'Keanu Reeves, Michael Nyqvist, Alfie Allen, Willem Dafoe' 2014 101 7.2
 321933 43.0 68.0]
[1054 'Action,Crime,Drama'
 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the Dark Knight must come to terms with one of the greatest psychological tests of his ability to fight injustice.'
 'Christopher Nolan'
 'Christian Bale, Heath Ledger, Aaron Eckhart,Michael Caine' 2008 152 9.0
 1791916 533.32 82.0]
[1055 'Adventure,Drama,History'
 'In the 17th century, two Portuguese Jesuit priests travel to Japan in an attempt to locate their mentor, who is rumored to have committed apostasy, and to propagate Catholicism.'
 'Martin Scorsese'
 'Andrew Garfield, Adam Driver, Liam Neeson,Tadanobu Asano' 2016 161 7.3
 49190 7.08 79.0]
[1056 'Crime,Horror,Thriller'
 "Hoping to walk away with a massive fortune, a trio of thieves break into the house of a blind man who isn't as helpless as he seems."
 'Fede Alvarez' 'Stephen Lang, Jane Levy, Dylan Minnette, Daniel Zovatto'
 2016 88 7.2 121103 89.21 71.0]
[1057 'Drama,Romance'
 "A girl in a small town forms an unlikely bond with a recently-paralyzed man she's taking care of."
 'Thea Sharrock' 'Emilia Clarke, Sam Claflin, Janet McTeer, Charles Dance'
 2016 106 7.4 113322 56.23 51.0]
[1058 'Comedy,Drama,Romance'
 'A former secretary, newly appointed as a scriptwriter for propaganda films, joins the cast and crew of a major production while the Blitz rages around them.'
 'Lone Scherfig' 'Gemma Arterton, Sam Claflin, Bill Nighy, Jack Huston'
 2016 117 7.0 3739 3.18 76.0]
[1059 'Biography,Drama'
 "The story of Chesley Sullenberger, an American pilot who became a hero after landing his damaged plane on the Hudson River in order to save the flight's passengers and crew."
 'Clint Eastwood'
 'Tom Hanks, Aaron Eckhart, Laura Linney, Valerie Mahaffey' 2016 96 7.5
 137608 125.07 74.0]
[1060 'Action,Adventure,Sci-Fi'
 'Fearing that the actions of Superman are left unchecked, Batman takes on the Man of Steel, while the world wrestles with what kind of a hero it really needs.'
 'Zack Snyder' 'Ben Affleck, Henry Cavill, Amy Adams, Jesse Eisenberg'
 2016 151 6.7 472307 330.25 44.0]
[1061 'Horror,Mystery,Thriller'
 'A father and son, both coroners, are pulled into a complex mystery while attempting to identify the body of a young woman, who was apparently harboring dark secrets.'
 'André Øvredal'
 'Brian Cox, Emile Hirsch, Ophelia Lovibond, Michael McElhatton' 2016 86
 6.8 35870 nan 65.0]
[1062 'Crime,Drama,Mystery'
 'A divorcee becomes entangled in a missing persons investigation that promises to send shockwaves throughout her life.'
 'Tate Taylor'
 'Emily Blunt, Haley Bennett, Rebecca Ferguson, Justin Theroux' 2016 112
 6.5 102177 75.31 48.0]
[1063 'Drama,Romance,Thriller'
 "Literature student Anastasia Steele's life changes forever when she meets handsome, yet tormented, billionaire Christian Grey."
 'Sam Taylor-Johnson'
 'Dakota Johnson, Jamie Dornan, Jennifer Ehle,Eloise Mumford' 2015 125 4.1
 244474 166.15 46.0]
[1064 'Drama,Mystery,Sci-Fi'
 'Two stage magicians engage in competitive one-upmanship in an attempt to create the ultimate stage illusion.'
 'Christopher Nolan'
 'Christian Bale, Hugh Jackman, Scarlett Johansson, Michael Caine' 2006
 130 8.5 913152 53.08 66.0]
[1065 'Action,Adventure,Comedy'
 "A spy organization recruits an unrefined, but promising street kid into the agency's ultra-competitive training program, just as a global threat emerges from a twisted tech genius."
 'Matthew Vaughn'
 'Colin Firth, Taron Egerton, Samuel L. Jackson,Michael Caine' 2014 129
 7.7 440209 128.25 58.0]
[1066 'Drama,History,Thriller'

 44227 nan nan]
[1966 'Adventure,Biography'
 "Highly influential and a fearlessly ambitious pioneer, innovator, filmmaker, researcher and conservationist, Jacques-Yves Cousteau's aquatic adventure covers roughly thirty years of an inarguably rich in achievements life."
 'Jérôme Salle'
 'Lambert Wilson, Pierre Niney, Audrey Tautou,Laurent Lucas' 2016 122 6.7
 1810 nan 70.0]
[1967 'Adventure,Biography,Crime'
 'In 1974, high-wire artist Philippe Petit recruits a team of people to help him realize his dream: to walk the immense void between the World Trade Center towers.'
 'Robert Zemeckis'
 'Joseph Gordon-Levitt, Charlotte Le Bon,Guillaume Baillargeon, Émilie Leclerc'
 2015 123 7.3 92378 10.14 nan]
[1968 'Action,Horror,Thriller'
 'Best friends Emily and Lesley go on a road trip to the desert. When Emily decides to get off the highway and take a "short cut," they become the target of a relentless and psychotic trucker... See full summary »'
 'Micheal Bafaro'
 'Anna Hutchison, Andrea Whitburn, Jennifer Koenig,Michael Dickson' 2015
 83 3.5 1210 nan 37.0]
[1969 'Action,Adventure,Western'
 'Native American warrior Tonto recounts the untold tales that transformed John Reid, a man of the law, into a legend of justice.'
 'Gore Verbinski'
 'Johnny Depp, Armie Hammer, William Fichtner,Tom Wilkinson' 2013 150 6.5
 190855 89.29 nan]
[1970 'Horror,Thriller'
 'A young woman travels to Texas to collect an inheritance; little does she know that an encounter with a chainsaw-wielding killer is part of the reward.'
 'John Luessenhop'
 'Alexandra Daddario, Tania Raymonde, Scott Eastwood, Trey Songz' 2013 92
 4.8 37060 34.33 62.0]
[1971 'Drama,Mystery,Thriller'
 'A teen living under house arrest becomes convinced his neighbor is a serial killer.'
 'D.J. Caruso' 'Shia LaBeouf, David Morse, Carrie-Anne Moss, Sarah Roemer'
 2007 105 6.9 193491 80.05 nan]
[1972 'Comedy,Drama,Musical'
 'A small town girl and a city boy meet on the Sunset Strip, while pursuing their Hollywood dreams.'
 'Adam Shankman' 'Julianne Hough, Diego Boneta, Tom Cruise, Alec Baldwin'
 2012 123 5.9 64513 38.51 47.0]
[1973 'Horror,Mystery'
 'Ten years have passed, and Sidney Prescott, who has put herself back together thanks in part to her writing, is visited by the Ghostface Killer.'
 'Wes Craven' 'Neve Campbell, Courteney Cox, David Arquette, Lucy Hale'
 2011 111 6.2 108544 38.18 52.0]
[1974 'Biography,Drama,Sport'
 'A Ugandan girl sees her world rapidly change after being introduced to the game of chess.'
 'Mira Nair'
 "Madina Nalwanga, David Oyelowo, Lupita Nyong'o, Martin Kabanza" 2016 124
 7.4 6753 8.81 73.0]
[1975 'Comedy,Family,Romance'
 'A Portokalos family secret brings the beloved characters back together for an even bigger and Greeker wedding.'
 'Kirk Jones'
 'Nia Vardalos, John Corbett, Michael Constantine, Lainie Kazan' 2016 94
 6.0 20966 59.57 37.0]
[1976 'Drama,Mystery,Thriller'
 'Libby Day was only eight years old when her family was brutally murdered in their rural Kansas farmhouse. Almost thirty years later, she reluctantly agrees to revisit the crime and uncovers the wrenching truths that led up to that tragic night.'
 'Gilles Paquet-Brenner'
 'Charlize Theron, Nicholas Hoult, Christina Hendricks, Chloë Grace Moretz'
 2015 113 6.2 31634 nan 39.0]
[1977 'Comedy'
 'Guy Carter is an award-winning graduate student of architecture. He\'s got a beautiful wife and a baby on the way. The problem? He doesn\'t have "his ducks in a row," which only fuels his ... See full summary »'
 'Lisa Addario'
 'Jason Biggs, Janet Montgomery,Ashley Tisdale, Bria L. Murphy' 2016 92
 5.0 2229 nan 38.0]
[1978 'Drama'
 'Louis (Gaspard Ulliel), a terminally ill writer, returns home after a long absence to tell his family that he is dying.'
 'Xavier Dolan'
 'Nathalie Baye, Vincent Cassel, Marion Cotillard, Léa Seydoux' 2016 97
 7.0 10658 nan 48.0]
[1979 'Drama,Thriller'
 'A brilliant plastic surgeon, haunted by past tragedies, creates a type of synthetic skin that withstands any kind of damage. His guinea pig: a mysterious and volatile woman who holds the key to his obsession.'
 'Pedro Almodóvar'
 'Antonio Banderas, Elena Anaya, Jan Cornet,Marisa Paredes' 2011 120 7.6
 108772 3.19 70.0]
[1980 'Biography,Drama,Family'
 'A young girl suffering from a rare digestive disorder finds herself miraculously cured after surviving a terrible accident.'
 'Patricia Riggen'
 'Jennifer Garner, Kylie Rogers, Martin Henderson,Brighton Sharbino' 2016
 109 7.0 12048 61.69 44.0]
[1981 'Comedy,Drama,Family'
 'A foster kid, who lives with her mean foster mom, sees her life change when business tycoon and New York mayoral candidate Will Stacks makes a thinly-veiled campaign move and takes her in.'
 'Will Gluck' 'Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, Rose Byrne'
 2014 118 5.3 27312 85.91 33.0]
[1982 'Drama,Fantasy,Musical'
 'The music of the Beatles and the Vietnam War form the backdrop for the romance between an upper-class American girl and a poor Liverpudlian artist.'
 'Julie Taymor' 'Evan Rachel Wood, Jim Sturgess, Joe Anderson, Dana Fuchs'
 2007 133 7.4 95172 24.34 56.0]
[1983 'Comedy'
 'Two struggling pals dress as police officers for a costume party and become neighborhood sensations. But when these newly-minted "heroes" get tangled in a real life web of mobsters and dirty detectives, they must put their fake badges on the line.'
 'Luke Greenfield'
 'Jake Johnson, Damon Wayans Jr., Rob Riggle, Nina Dobrev' 2014 104 6.5
 112729 82.39 30.0]
[1984 'Adventure,Family'
 "A Malinois dog that helped American Marines in Afghanistan returns to the United States and is adopted by his handler's family after suffering a traumatic experience."
 'Boaz Yakin'
 'Thomas Haden Church, Josh Wiggins, Luke Kleintank,Lauren Graham' 2015
 111 6.8 21405 42.65 47.0]
[1985 'Adventure,Comedy,Fantasy'
 "When Prince Fabious's bride is kidnapped, he goes on a quest to rescue her... accompanied by his lazy useless brother Thadeous."
 'David Gordon Green'
 'Danny McBride, Natalie Portman, James Franco, Rasmus Hardiker' 2011 102
 5.6 87904 21.56 31.0]
[1986 'Horror,Thriller'
 "Survivors of a suspension-bridge collapse learn there's no way you can cheat Death."
 'Steven Quale'
 "Nicholas D'Agosto, Emma Bell, Arlen Escarpeta, Miles Fisher" 2011 92 5.9
 88000 42.58 50.0]
[1987 'Drama,Romance'
 'The story of a privileged girl and a charismatic boy whose instant desire sparks a love affair made only more reckless by parents trying to keep them apart.'
 'Shana Feste'
 'Gabriella Wilde, Alex Pettyfer, Bruce Greenwood,Robert Patrick' 2014 104
 6.3 33688 23.39 30.0]
[1988 'Horror'
 "A young woman's quest for revenge against the people who kidnapped and tormented her as a child leads her and a friend, who is also a victim of child abuse, on a terrifying journey into a living hell of depravity."
 'Pascal Laugier'
 'Morjana Alaoui, Mylène Jampanoï, Catherine Bégin,Robert Toupin' 2008 99
 7.1 63785 nan 89.0]
[1989 'Biography,Drama,History'
 "A chronicle of Martin Luther King's campaign to secure equal voting rights via an epic march from Selma to Montgomery, Alabama in 1965."
 'Ava DuVernay'
 'David Oyelowo, Carmen Ejogo, Tim Roth, Lorraine Toussaint' 2014 128 7.5
 67637 52.07 nan]
[1990 'Action,Adventure,Fantasy'
 'An origins story centered on the centuries-old feud between the race of aristocratic vampires and their onetime slaves, the Lycans.'
 'Patrick Tatopoulos'
 'Rhona Mitra, Michael Sheen, Bill Nighy, Steven Mackintosh' 2009 92 6.6
 129708 45.8 44.0]
[1991 'Drama,Family,Music'
 'An eight-year-old boy is thought to be a lazy trouble-maker, until the new art teacher has the patience and compassion to discover the real problem behind his struggles in school.'
 'Aamir Khan' 'Darsheel Safary, Aamir Khan, Tanay Chheda, Sachet Engineer'
 2007 165 8.5 102697 1.2 42.0]
[1992 'Comedy,Drama,Romance'
 "Four years after graduation, an awkward high school genius uses his sister's boyfriend's Labor Day party as the perfect opportunity to make his move on his high school crush."
 'Michael Dowse' 'Topher Grace, Anna Faris, Dan Fogler, Teresa Palmer'
 2011 97 6.3 45419 6.92 nan]
[1993 'Action,Adventure,Horror'
 'While still out to destroy the evil Umbrella Corporation, Alice joins a group of survivors living in a prison surrounded by the infected who also want to relocate to the mysterious but supposedly unharmed safe haven known only as Arcadia.'
 'Paul W.S. Anderson'
 'Milla Jovovich, Ali Larter, Wentworth Miller,Kim Coates' 2010 97 5.9
 140900 60.13 37.0]
[1994 'Comedy'
 '3 high school seniors throw a birthday party to make a name for themselves. As the night progresses, things spiral out of control as word of the party spreads.'
 'Nima Nourizadeh'
 'Thomas Mann, Oliver Cooper, Jonathan Daniel Brown, Dax Flame' 2012 88
 6.7 164088 54.72 48.0]
[1995 'Crime,Drama,Mystery'
 'A tight-knit team of rising investigators, along with their supervisor, is suddenly torn apart when they discover that one of their own teenage daughters has been brutally murdered.'
 'Billy Ray' 'Chiwetel Ejiofor, Nicole Kidman, Julia Roberts, Dean Norris'
 2015 111 6.2 27585 nan 45.0]
[1996 'Horror'
 'Three American college students studying abroad are lured to a Slovakian hostel, and discover the grim reality behind it.'
 'Eli Roth' 'Lauren German, Heather Matarazzo, Bijou Phillips, Roger Bart'
 2007 94 5.5 73152 17.54 46.0]
[1997 'Drama,Music,Romance'
 'Romantic sparks occur between two dance students from different backgrounds at the Maryland School of the Arts.'
 'Jon M. Chu'
 'Robert Hoffman, Briana Evigan, Cassie Ventura, Adam G. Sevani' 2008 98
 6.2 70699 58.01 50.0]
[1998 'Adventure,Comedy'
 'A pair of friends embark on a mission to reunite their pal with the woman he was going to marry.'
 'Scot Armstrong'
 'Adam Pally, T.J. Miller, Thomas Middleditch,Shannon Woodward' 2014 93
 5.6 4881 nan 22.0]
[1999 'Comedy,Family,Fantasy'
 "A stuffy businessman finds himself trapped inside the body of his family's cat."
 'Barry Sonnenfeld'
 'Kevin Spacey, Jennifer Garner, Robbie Amell,Cheryl Hines' 2016 87 5.3
 12435 19.64 11.0]

In [180]:
movies_df.columns = col_low
movies_df

,rank,genre,desc,director,actors,year,runtime,rating,votes,revenue,metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1000,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,1001,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,1002,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,1003,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,1004,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,1995,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,1996,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,1997,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,1998,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1999,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [181]:
sample_df = movies_df.loc[:,['rank','year']]

In [182]:
sample_df

                         rank  year
Title
Guardians of the Galaxy  1000  2014
Prometheus               1001  2012
Split                    1002  2016
Sing                     1003  2016
Suicide Squad            1004  2016
...                       ...   ...
Secret in Their Eyes     1995  2015
Hostel: Part II          1996  2007
Step Up 2: The Streets   1997  2008
Search Party             1998  2014
Nine Lives               1999  2016

[1000 rows x 2 columns]

In [188]:
sample_df = movies_df.loc[(movies_df['rank'] == 1003) & (movies_df['year'] == 2016)]
sample_df

,rank,genre,desc,director,actors,year,runtime,rating,votes,revenue,metascore
Title,,,,,,,,,,,
Sing,1003,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0

In [191]:
for i in movies_df['genre']:
    if type(i) == str:
        print('Yes')

Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes
Yes

In [192]:
list1 = list(movies_df.values)
list1

[array([1000, 'Action,Adventure,Sci-Fi',
        'A group of intergalactic criminals are forced to work together to stop a fanatical warrior from taking control of the universe.',
        'James Gunn',
        'Chris Pratt, Vin Diesel, Bradley Cooper, Zoe Saldana', 2014, 121,
        8.1, 757074, 333.13, 76.0], dtype=object),
 array([1001, 'Adventure,Mystery,Sci-Fi',
        'Following clues to the origin of mankind, a team finds a structure on a distant moon, but they soon realize they are not alone.',
        'Ridley Scott',
        'Noomi Rapace, Logan Marshall-Green, Michael Fassbender, Charlize Theron',
        2012, 124, 7.0, 485820, 126.46, 65.0], dtype=object),
 array([1002, 'Horror,Thriller',
        'Three girls are kidnapped by a man with a diagnosed 23 distinct personalities. They must try to escape before the apparent emergence of a frightful new 24th.',
        'M. Night Shyamalan',
        'James McAvoy, Anya Taylor-Joy, Haley Lu Richardson, Jessica Sula',
        2016, 117, 7.3, 157606, 138.12, 62.0], dtype=object),
 array([1003, 'Animation,Comedy,Family',
        "In a city of humanoid animals, a hustling theater impresario's attempt to save his theater with a singing competition becomes grander than he anticipates even as its finalists' find that their lives will never be the same.",
        'Christophe Lourdelet',
        'Matthew McConaughey,Reese Witherspoon, Seth MacFarlane, Scarlett Johansson',
        2016, 108, 7.2, 60545, 270.32, 59.0], dtype=object),
 array([1004, 'Action,Adventure,Fantasy',
        'A secret government agency recruits some of the most dangerous incarcerated super-villains to form a defensive task force. Their first mission: save the world from the apocalypse.',
        'David Ayer', 'Will Smith, Jared Leto, Margot Robbie, Viola Davis',
        2016, 123, 6.2, 393727, 325.02, 40.0], dtype=object),
 array([1005, 'Action,Adventure,Fantasy',
        'European mercenaries searching for black powder become embroiled in the defense of the Great Wall of China against a horde of monstrous creatures.',
        'Yimou Zhang', 'Matt Damon, Tian Jing, Willem Dafoe, Andy Lau',
        2016, 103, 6.1, 56036, 45.13, 42.0], dtype=object),
 array([1006, 'Comedy,Drama,Music',
        'A jazz pianist falls for an aspiring actress in Los Angeles.',
        'Damien Chazelle',
        'Ryan Gosling, Emma Stone, Rosemarie DeWitt, J.K. Simmons', 2016,
        128, 8.3, 258682, 151.06, 93.0], dtype=object),
 array([1007, 'Comedy',
        'A has-been actor best known for playing the title character in the 1980s detective series "Mindhorn" must work with the police when a serial killer says that he will only speak with Detective Mindhorn, whom he believes to be a real person.',
        'Sean Foley',
        'Essie Davis, Andrea Riseborough, Julian Barratt,Kenneth Branagh',
        2016, 89, 6.4, 2490, nan, 71.0], dtype=object),
 array([1008, 'Action,Adventure,Biography',
        'A true-life drama, centering on British explorer Col. Percival Fawcett, who disappeared while searching for a mysterious city in the Amazon in the 1920s.',
        'James Gray',
        'Charlie Hunnam, Robert Pattinson, Sienna Miller, Tom Holland',
        2016, 141, 7.1, 7188, 8.01, 78.0], dtype=object),
 array([1009, 'Adventure,Drama,Romance',
        'A spacecraft traveling to a distant colony planet and transporting thousands of people has a malfunction in its sleep chambers. As a result, two passengers are awakened 90 years early.',
        'Morten Tyldum',
        'Jennifer Lawrence, Chris Pratt, Michael Sheen,Laurence Fishburne',
        2016, 116, 7.0, 192177, 100.01, 41.0], dtype=object),
 array([1010, 'Adventure,Family,Fantasy',
        "The adventures of writer Newt Scamander in New York's secret community of witches and wizards seventy years before Harry Potter reads his book in school.",
        'David Yates',
        'Eddie Redmayne, Katherine Waterston, Alison Sudol,Dan Fogler',
        2016, 133, 7.5, 232072, 234.02, 66.0], dtype=object),
 array([1011, 'Biography,Drama,History',
        'The story of a team of female African-American mathematicians who served a vital role in NASA during the early years of the U.S. space program.',
        'Theodore Melfi',
        'Taraji P. Henson, Octavia Spencer, Janelle Monáe,Kevin Costner',
        2016, 127, 7.8, 93103, 169.27, 74.0], dtype=object),
 array([1012, 'Action,Adventure,Sci-Fi',
        'The Rebel Alliance makes a risky move to steal the plans for the Death Star, setting up the epic saga to follow.',
        'Gareth Edwards',
        'Felicity Jones, Diego Luna, Alan Tudyk, Donnie Yen', 2016, 133,
        7.9, 323118, 532.17, 65.0], dtype=object),
 array([1013, 'Animation,Adventure,Comedy',
        "In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches an impetuous Chieftain's daughter's island, she answers the Ocean's call to seek out the Demigod to set things right.",
        'Ron Clements',
        "Auli'i Cravalho, Dwayne Johnson, Rachel House, Temuera Morrison",
        2016, 107, 7.7, 118151, 248.75, 81.0], dtype=object),
 array([1014, 'Action,Comedy,Drama',
        'Gloria is an out-of-work party girl forced to leave her life in New York City, and move back home. When reports surface that a giant creature is destroying Seoul, she gradually comes to the realization that she is somehow connected to this phenomenon.',
        'Nacho Vigalondo',
        'Anne Hathaway, Jason Sudeikis, Austin Stowell,Tim Blake Nelson',
        2016, 109, 6.4, 8612, 2.87, 70.0], dtype=object),
 array([1015, 'Animation,Adventure,Comedy',
        'The quiet life of a terrier named Max is upended when his owner takes in Duke, a stray whom Max instantly dislikes.',
        'Chris Renaud',
        'Louis C.K., Eric Stonestreet, Kevin Hart, Lake Bell', 2016, 87,
        6.6, 120259, 368.31, 61.0], dtype=object),
 array([1016, 'Biography,Drama,History',
        'WWII American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people, and becomes the first man in American history to receive the Medal of Honor without firing a shot.',
        'Mel Gibson',
        'Andrew Garfield, Sam Worthington, Luke Bracey,Teresa Palmer',
        2016, 139, 8.2, 211760, 67.12, 71.0], dtype=object),
 array([1017, 'Action,Thriller',
        "The CIA's most dangerous former operative is drawn out of hiding to uncover more explosive truths about his past.",
        'Paul Greengrass',
        'Matt Damon, Tommy Lee Jones, Alicia Vikander,Vincent Cassel',
        2016, 123, 6.7, 150823, 162.16, 58.0], dtype=object),
 array([1018, 'Biography,Drama',
        'A five-year-old Indian boy gets lost on the streets of Calcutta, thousands of kilometers from home. He survives many challenges before being adopted by a couple in Australia. 25 years later, he sets out to find his lost family.',
        'Garth Davis',
        'Dev Patel, Nicole Kidman, Rooney Mara, Sunny Pawar', 2016, 118,
        8.1, 102061, 51.69, 69.0], dtype=object),
 array([1019, 'Drama,Mystery,Sci-Fi',
        'When twelve mysterious spacecraft appear around the world, linguistics professor Louise Banks is tasked with interpreting the language of the apparent alien visitors.',
        'Denis Villeneuve',
        'Amy Adams, Jeremy Renner, Forest Whitaker,Michael Stuhlbarg',
        2016, 116, 8.0, 340798, 100.5, 81.0], dtype=object),
 array([1020, 'Adventure,Drama,Thriller',
        'Kenny Wells, a prospector desperate for a lucky break, teams up with a similarly eager geologist and sets off on a journey to find gold in the uncharted jungle of Indonesia.',
        'Stephen Gaghan',
        'Matthew McConaughey, Edgar Ramírez, Bryce Dallas Howard, Corey Stoll',
        2016, 120, 6.7, 19053, 7.22, 49.0], dtype=object),
 array([1021, 'Drama',
        "A depressed uncle is asked to take care of his teenage nephew after the boy's father dies.",
        'Kenneth Lonergan',
        'Casey Affleck, Michelle Williams, Kyle Chandler,Lucas Hedges',
        2016, 137, 7.9, 134213, 47.7, 96.0], dtype=object),
 array([1022, 'Crime,Drama,Horror',
        "A cold-blooded predatory couple while cruising the streets in search of their next victim, will stumble upon a 17-year-old high school girl, who will be sedated, abducted and chained in the strangers' guest room.",
        'Ben Young',
        'Emma Booth, Ashleigh Cummings, Stephen Curry,Susie Porter', 2016,
        108, 6.7, 1115, nan, 72.0], dtype=object),
 array([1023, 'Animation,Adventure,Comedy',
        'After the Bergens invade Troll Village, Poppy, the happiest Troll ever born, and the curmudgeonly Branch set off on a journey to rescue her friends.',
        'Walt Dohrn',
        'Anna Kendrick, Justin Timberlake,Zooey Deschanel, Christopher Mintz-Plasse',
        2016, 92, 6.5, 38552, 153.69, 56.0], dtype=object),
 array([1024, 'Action,Adventure,Sci-Fi',
        "Two decades after the first Independence Day invasion, Earth is faced with a new extra-Solar threat. But will mankind's new space defenses be enough?",
        'Roland Emmerich',
        'Liam Hemsworth, Jeff Goldblum, Bill Pullman,Maika Monroe', 2016,
        120, 5.3, 127553, 103.14, 32.0], dtype=object),
 array([1025, 'Comedy',
        'Fiona visits Paris for the first time to assist her myopic Aunt Martha. Catastrophes ensue, mainly involving Dom, a homeless man who has yet to have an emotion or thought he was afraid of expressing.',
        'Dominique Abel',
        'Fiona Gordon, Dominique Abel,Emmanuelle Riva, Pierre Richard',
        2016, 83, 6.8, 222, nan, nan], dtype=object),
 array([1026, 'Action,Adventure,Drama',
        'In ancient India, an adventurous and daring man becomes involved in a decades old feud between two warring people.',
        'S.S. Rajamouli',
        'Prabhas, Rana Daggubati, Anushka Shetty,Tamannaah Bhatia', 2015,
        159, 8.3, 76193, 6.5, nan], dtype=object),
 array([1027, 'Horror,Thriller',
        'A young woman must save herself and her friends from an ancient evil that stalks its victims through the real-life phenomenon of sleep paralysis.',
        'Phillip Guzman',
        'Jocelin Donahue, Jesse Bradford, Jesse Borrego,Lori Petty', 2016,
        99, 4.7, 523, 0.01, nan], dtype=object),
 array([1028, 'Comedy',
        'When three overworked and under-appreciated moms are pushed beyond their limits, they ditch their conventional responsibilities for a jolt of long overdue freedom, fun, and comedic self-indulgence.',
        'Jon Lucas',
        'Mila Kunis, Kathryn Hahn, Kristen Bell,Christina Applegate', 2016,
        100, 6.2, 66540, 113.08, 60.0], dtype=object),
 array([1029, 'Action,Adventure,Drama',
        'When Callum Lynch explores the memories of his ancestor Aguilar and gains the skills of a Master Assassin, he discovers he is a descendant of the secret Assassins society.',
        'Justin Kurzel',
        'Michael Fassbender, Marion Cotillard, Jeremy Irons,Brendan Gleeson',
        2016, 115, 5.9, 112813, 54.65, 36.0], dtype=object),
 array([1030, 'Comedy',
        "A holiday gathering threatens to go off the rails when Ned Fleming realizes that his daughter's Silicon Valley millionaire boyfriend is about to pop the question.",
        'John Hamburg',
        'Zoey Deutch, James Franco, Tangie Ambrose,Cedric the Entertainer',
        2016, 111, 6.3, 48123, 60.31, 39.0], dtype=object),
 array([1031, 'Drama,Thriller',
        "A wealthy art gallery owner is haunted by her ex-husband's novel, a violent thriller she interprets as a symbolic revenge tale.",
        'Tom Ford',
        'Amy Adams, Jake Gyllenhaal, Michael Shannon, Aaron Taylor-Johnson',
        2016, 116, 7.5, 126030, 10.64, 67.0], dtype=object),
 array([1032, 'Action,Adventure,Sci-Fi',
        "After the re-emergence of the world's first mutant, world-destroyer Apocalypse, the X-Men must unite to defeat his extinction level plan.",
        'Bryan Singer',
        'James McAvoy, Michael Fassbender, Jennifer Lawrence, Nicholas Hoult',
        2016, 144, 7.1, 275510, 155.33, 52.0], dtype=object),
 array([1033, 'Action,Adventure,Comedy',
        'A fast-talking mercenary with a morbid sense of humor is subjected to a rogue experiment that leaves him with accelerated healing powers and a quest for revenge.',
        'Tim Miller',
        'Ryan Reynolds, Morena Baccarin, T.J. Miller, Ed Skrein', 2016,
        108, 8.0, 627797, 363.02, 65.0], dtype=object),
 array([1034, 'Action,Horror,Sci-Fi',
        'Alice returns to where the nightmare began: The Hive in Raccoon City, where the Umbrella Corporation is gathering its forces for a final strike against the only remaining survivors of the apocalypse.',
        'Paul W.S. Anderson',
        'Milla Jovovich, Iain Glen, Ali Larter, Shawn Roberts', 2016, 107,
        5.6, 46165, 26.84, 49.0], dtype=object),
 array([1035, 'Action,Adventure,Sci-Fi',
        "Political interference in the Avengers' activities causes a rift between former allies Captain America and Iron Man.",
        'Anthony Russo',
        'Chris Evans, Robert Downey Jr.,Scarlett Johansson, Sebastian Stan',
        2016, 147, 7.9, 411656, 408.08, 75.0], dtype=object),
 array([1036, 'Adventure,Drama,Sci-Fi',
        "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        'Christopher Nolan',
        'Matthew McConaughey, Anne Hathaway, Jessica Chastain, Mackenzie Foy',
        2014, 169, 8.6, 1047747, 187.99, 74.0], dtype=object),
 array([1037, 'Action,Adventure,Fantasy',
        'While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.',
        'Scott Derrickson',
        'Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams, Benedict Wong',
        2016, 115, 7.6, 293732, 232.6, 72.0], dtype=object),
 array([1038, 'Action,Adventure,Western',
        'Seven gunmen in the old west gradually come together to help a poor village against savage thieves.',
        'Antoine Fuqua',
        "Denzel Washington, Chris Pratt, Ethan Hawke,Vincent D'Onofrio",
        2016, 132, 6.9, 122853, 93.38, 54.0], dtype=object),
 array([1039, 'Comedy,Drama',
        "Alienated, hopeful-filmmaker Pat Johnson's epic story growing up in rural Illinois, falling in love, and becoming the first fan of the movie that changed everything.",
        'Patrick Read Johnson',
        'John Francis Daley, Austin Pendleton, Colleen Camp, Neil Flynn',
        2007, 113, 7.1, 241, nan, nan], dtype=object),
 array([1040, 'Animation,Adventure,Comedy',
        'A sausage strives to discover the truth about his existence.',
        'Greg Tiernan',
        'Seth Rogen, Kristen Wiig, Jonah Hill, Alistair Abell', 2016, 89,
        6.3, 120690, 97.66, 66.0], dtype=object),
 array([1041, 'Drama',
        'A chronicle of the childhood, adolescence and burgeoning adulthood of a young, African-American, gay man growing up in a rough neighborhood of Miami.',
        'Barry Jenkins',
        'Mahershala Ali, Shariff Earp, Duan Sanderson, Alex R. Hibbert',
        2016, 111, 7.5, 135095, 27.85, 99.0], dtype=object),
 array([1042, 'Horror',
        'A group of friends are going on a camping trip to celebrate graduating college. But once they enter the woods, the proverbial shit starts to hit the fan.',
        'Shawn Burkett',
        'Brittany Blanton, Ayse Howard, Roman Jossart,Nadia White', 2016,
        73, 2.7, 496, nan, nan], dtype=object),
 array([1043, 'Biography,Drama,History',
        "The story of Ray Kroc, a salesman who turned two brothers' innovative fast food eatery, McDonald's, into one of the biggest restaurant businesses in the world with a combination of ambition, persistence, and ruthlessness.",
        'John Lee Hancock',
        'Michael Keaton, Nick Offerman, John Carroll Lynch, Linda Cardellini',
        2016, 115, 7.2, 37033, 12.79, 66.0], dtype=object),
 array([1044, 'Drama',
        "A young street artist in East Los Angeles is caught between his father's obsession with lowrider car culture, his ex-felon brother and his need for self-expression.",
        'Ricardo de Montreuil',
        'Gabriel Chavarria, Demián Bichir, Theo Rossi,Tony Revolori', 2016,
        99, 6.3, 279, 4.21, 57.0], dtype=object),
 array([1045, 'Action,Adventure,Fantasy',
        'Jack Sparrow and Barbossa embark on a quest to find the elusive fountain of youth, only to discover that Blackbeard and his daughter are after it too.',
        'Rob Marshall',
        'Johnny Depp, Penélope Cruz, Ian McShane, Geoffrey Rush', 2011,
        136, 6.7, 395025, 241.06, 45.0], dtype=object),
 array([1046, 'Drama,Thriller',
        'In the high-stakes world of political power-brokers, Elizabeth Sloane is the most sought after and formidable lobbyist in D.C. But when taking on the most powerful opponent of her career, she finds winning may come at too high a price.',
        'John Madden',
        'Jessica Chastain, Mark Strong, Gugu Mbatha-Raw,Michael Stuhlbarg',
        2016, 132, 7.3, 17818, 3.44, 64.0], dtype=object),
 array([1047, 'Adventure,Drama,Fantasy',
        'A young girl finds herself in a reform school after therapy since she was blamed for the death of a young boy. At the school she finds herself drawn to a fellow student, unaware that he is an angel, and has loved her for thousands of years.',
        'Scott Hicks',
        'Hermione Corfield, Addison Timlin, Joely Richardson,Jeremy Irvine',
        2016, 91, 5.6, 5103, nan, nan], dtype=object),
 array([1048, 'Action,Adventure,Sci-Fi',
        'The USS Enterprise crew explores the furthest reaches of uncharted space, where they encounter a new ruthless enemy who puts them and everything the Federation stands for to the test.',
        'Justin Lin',
        'Chris Pine, Zachary Quinto, Karl Urban, Zoe Saldana', 2016, 122,
        7.1, 164567, 158.8, 68.0], dtype=object),
 array([1049, 'Drama',
        'A director (Charlize Theron) of an international aid agency in Africa meets a relief aid doctor (Javier Bardem) amidst a political/social revolution, and together face tough choices ... See full summary »',
        'Sean Penn',
        'Charlize Theron, Javier Bardem, Adèle Exarchopoulos,Jared Harris',
        2016, 130, 3.7, 987, nan, 16.0], dtype=object),
 array([1050, 'Action,Adventure,Fantasy',
        'Three decades after the defeat of the Galactic Empire, a new threat arises. The First Order attempts to rule the galaxy and only a ragtag group of heroes can stop them, along with the help of the Resistance.',
        'J.J. Abrams',
        'Daisy Ridley, John Boyega, Oscar Isaac, Domhnall Gleeson', 2015,
        136, 8.1, 661608, 936.63, 81.0], dtype=object),
 array([1051, 'Action,Adventure,Fantasy',
        'Vampire death dealer, Selene (Kate Beckinsale) fights to end the eternal war between the Lycan clan and the Vampire faction that betrayed her.',
        'Anna Foerster',
        'Kate Beckinsale, Theo James, Tobias Menzies, Lara Pulver', 2016,
        91, 5.8, 41362, 30.35, 23.0], dtype=object),
 array([1052, 'Comedy,Drama',
        "Three generations come together in the week leading up to Mother's Day.",
        'Garry Marshall',
        'Jennifer Aniston, Kate Hudson, Julia Roberts, Jason Sudeikis',
        2016, 118, 5.6, 20221, 32.46, 18.0], dtype=object),
 array([1053, 'Action,Crime,Thriller',
        'An ex-hitman comes out of retirement to track down the gangsters that took everything from him.',
        'Chad Stahelski',
        'Keanu Reeves, Michael Nyqvist, Alfie Allen, Willem Dafoe', 2014,
        101, 7.2, 321933, 43.0, 68.0], dtype=object),
 array([1054, 'Action,Crime,Drama',
        'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the Dark Knight must come to terms with one of the greatest psychological tests of his ability to fight injustice.',
        'Christopher Nolan',
        'Christian Bale, Heath Ledger, Aaron Eckhart,Michael Caine', 2008,

# Null Values

In [195]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, Guardians of the Galaxy to Nine Lives
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   rank       1000 non-null   int32
 1   genre      1000 non-null   object
 2   desc       1000 non-null   object
 3   director   1000 non-null   object
 4   actors     1000 non-null   object
 5   year       1000 non-null   int64
 6   runtime    1000 non-null   int64
 7   rating     1000 non-null   float64
 8   votes      1000 non-null   int64
 9   revenue    872 non-null    float64
 10  metascore  936 non-null    float64
dtypes: float64(3), int32(1), int64(3), object(4)
memory usage: 129.8+ KB

In [197]:
movies_df.isna().sum()

rank           0
genre          0
desc           0
director       0
actors         0
year           0
runtime        0
rating         0
votes          0
revenue      128
metascore     64
dtype: int64

In [199]:
movies_df[movies_df['metascore'].isna() == True]

,rank,genre,desc,director,actors,year,runtime,rating,votes,revenue,metascore
Title,,,,,,,,,,,
Paris pieds nus,1025,Comedy,Fiona visits Paris for the first time to assis...,Dominique Abel,"Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...",2016,83,6.8,222,NaN,NaN
Bahubali: The Beginning,1026,"Action,Adventure,Drama","In ancient India, an adventurous and daring ma...",S.S. Rajamouli,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",2015,159,8.3,76193,6.50,NaN
Dead Awake,1027,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,NaN
5- 25- 77,1039,"Comedy,Drama","Alienated, hopeful-filmmaker Pat Johnson's epi...",Patrick Read Johnson,"John Francis Daley, Austin Pendleton, Colleen ...",2007,113,7.1,241,NaN,NaN
Don't Fuck in the Woods,1042,Horror,A group of friends are going on a camping trip...,Shawn Burkett,"Brittany Blanton, Ayse Howard, Roman Jossart,N...",2016,73,2.7,496,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
The Walk,1967,"Adventure,Biography,Crime","In 1974, high-wire artist Philippe Petit recru...",Robert Zemeckis,"Joseph Gordon-Levitt, Charlotte Le Bon,Guillau...",2015,123,7.3,92378,10.14,NaN
The Lone Ranger,1969,"Action,Adventure,Western",Native American warrior Tonto recounts the unt...,Gore Verbinski,"Johnny Depp, Armie Hammer, William Fichtner,To...",2013,150,6.5,190855,89.29,NaN
Disturbia,1971,"Drama,Mystery,Thriller",A teen living under house arrest becomes convi...,D.J. Caruso,"Shia LaBeouf, David Morse, Carrie-Anne Moss, S...",2007,105,6.9,193491,80.05,NaN
Selma,1989,"Biography,Drama,History",A chronicle of Martin Luther King's campaign t...,Ava DuVernay,"David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...",2014,128,7.5,67637,52.07,NaN
Take Me Home Tonight,1992,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,NaN

In [201]:
movies_df.isna().sum()

rank           0
genre          0
desc           0
director       0
actors         0
year           0
runtime        0
rating         0
votes          0
revenue      128
metascore     64
dtype: int64

In [202]:
movies_df = movies_df.dropna()

In [203]:
movies_df.shape

(838, 11)

In [204]:
movies_df.describe()

,rank,year,runtime,rating,votes,revenue,metascore
count,838.000000,838.00000,838.000000,838.000000,8.380000e+02,838.000000,838.000000
mean,1484.247017,2012.50716,114.638425,6.814320,1.932303e+05,84.564558,59.575179
std,286.572065,3.17236,18.470922,0.877754,1.930990e+05,104.520227,16.952416
min,1000.000000,2006.00000,66.000000,1.900000,1.780000e+02,0.000000,11.000000
25%,1237.250000,2010.00000,101.000000,6.300000,6.127650e+04,13.967500,47.000000
50%,1474.500000,2013.00000,112.000000,6.900000,1.368795e+05,48.150000,60.000000
75%,1728.750000,2015.00000,124.000000,7.500000,2.710830e+05,116.800000,72.000000
max,1999.000000,2016.00000,187.000000,9.000000,1.791916e+06,936.630000,100.000000

In [205]:
movies_df['year'].describe()

count     838.00000
mean     2012.50716
std         3.17236
min      2006.00000
25%      2010.00000
50%      2013.00000
75%      2015.00000
max      2016.00000
Name: year, dtype: float64

In [208]:
movies_df['genre'].value_counts().head(10)

Action,Adventure,Sci-Fi       50
Comedy,Drama,Romance          30
Drama                         29
Drama,Romance                 27
Animation,Adventure,Comedy    26
Comedy                        26
Action,Adventure,Fantasy      25
Comedy,Drama                  24
Comedy,Romance                22
Crime,Drama,Thriller          18
Name: genre, dtype: int64

In [210]:
movies_df.count()

rank         838
genre        838
desc         838
director     838
actors       838
year         838
runtime      838
rating       838
votes        838
revenue      838
metascore    838
dtype: int64

In [211]:
movies_df.corr()

,rank,year,runtime,rating,votes,revenue,metascore
rank,1.000000,-0.312809,-0.254783,-0.243125,-0.303284,-0.273170,-0.195909
year,-0.312809,1.000000,-0.101933,-0.145703,-0.362445,-0.129198,-0.062303
runtime,-0.254783,-0.101933,1.000000,0.374566,0.399298,0.281721,0.221397
rating,-0.243125,-0.145703,0.374566,1.000000,0.517452,0.217106,0.672731
votes,-0.303284,-0.362445,0.399298,0.517452,1.000000,0.636833,0.332674
revenue,-0.273170,-0.129198,0.281721,0.217106,0.636833,1.000000,0.142397
metascore,-0.195909,-0.062303,0.221397,0.672731,0.332674,0.142397,1.000000

In [218]:
cond = movies_df['director'] == 'David Ayer'
cond.head()

Title
Guardians of the Galaxy    False
Prometheus                 False
Split                      False
Sing                       False
Suicide Squad               True
Name: director, dtype: bool

In [225]:
movies_df[(movies_df['rating']) > 8.3].head(10)

,rank,genre,desc,director,actors,year,runtime,rating,votes,revenue,metascore
Title,,,,,,,,,,,
Interstellar,1036,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
The Dark Knight,1054,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
The Prestige,1064,"Drama,Mystery,Sci-Fi",Two stage magicians engage in competitive one-...,Christopher Nolan,"Christian Bale, Hugh Jackman, Scarlett Johanss...",2006,130,8.5,913152,53.08,66.0
Inception,1080,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0
Kimi no na wa,1096,"Animation,Drama,Fantasy",Two strangers find themselves linked in a biza...,Makoto Shinkai,"Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Nari...",2016,106,8.6,34110,4.68,79.0
The Departed,1099,"Crime,Drama,Thriller",An undercover cop and a mole in the police att...,Martin Scorsese,"Leonardo DiCaprio, Matt Damon, Jack Nicholson,...",2006,151,8.5,937414,132.37,85.0
The Dark Knight Rises,1124,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.0
Whiplash,1133,"Drama,Music",A promising young drummer enrolls at a cut-thr...,Damien Chazelle,"Miles Teller, J.K. Simmons, Melissa Benoist, P...",2014,107,8.5,477276,13.09,88.0
Django Unchained,1144,"Drama,Western","With the help of a German bounty hunter , a fr...",Quentin Tarantino,"Jamie Foxx, Christoph Waltz, Leonardo DiCaprio...",2012,165,8.4,1039115,162.80,81.0
The Intouchables,1249,"Biography,Comedy,Drama",After he becomes a quadriplegic from a paragli...,Olivier Nakache,"François Cluzet, Omar Sy, Anne Le Ny, Audrey F...",2011,112,8.6,557965,13.18,57.0

In [227]:
movies_df.loc[(movies_df['year'] == 2016) | (movies_df['runtime'] == 87)]

,rank,genre,desc,director,actors,year,runtime,rating,votes,revenue,metascore
Title,,,,,,,,,,,
Split,1002,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,1003,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,1004,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
The Great Wall,1005,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
La La Land,1006,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
...,...,...,...,...,...,...,...,...,...,...,...
Kicks,1949,Adventure,Brandon is a 15 year old whose dream is a pair...,Justin Tipping,"Jahking Guillory, Christopher Jordan Wallace,C...",2016,80,6.1,2417,0.15,69.0
Queen of Katwe,1974,"Biography,Drama,Sport",A Ugandan girl sees her world rapidly change a...,Mira Nair,"Madina Nalwanga, David Oyelowo, Lupita Nyong'o...",2016,124,7.4,6753,8.81,73.0
My Big Fat Greek Wedding 2,1975,"Comedy,Family,Romance",A Portokalos family secret brings the beloved ...,Kirk Jones,"Nia Vardalos, John Corbett, Michael Constantin...",2016,94,6.0,20966,59.57,37.0
Miracles from Heaven,1980,"Biography,Drama,Family",A young girl suffering from a rare digestive d...,Patricia Riggen,"Jennifer Garner, Kylie Rogers, Martin Henderso...",2016,109,7.0,12048,61.69,44.0
Nine Lives,1999,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [235]:
movies_df[movies_df['year'].isin([2016])].head()

,rank,genre,desc,director,actors,year,runtime,rating,votes,revenue,metascore
Title,,,,,,,,,,,
Split,1002,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,1003,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,1004,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
The Great Wall,1005,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
La La Land,1006,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0